### ISSUE TITLE
No se guardan las configuraciones

### ISSUE THREAD

**Issue by cfficaurzua** [khipu/woocommerce-khipu-gateway#8]
Al hacer click en cualquier button-toggle para activar el servicio de khipu, no hace ninguna acción.
hay que hacer un segundo click para que cambie de estado
admin-ajax.php responde con {"success":true,"data":false}, para el primer click y con {"success":true,"data":true}
para el segundo.
 después de apretar guardar cambios estos no se guardan.
![bug khipu-min](https://user-images.githubusercontent.com/13381072/91076980-5187b400-e60e-11ea-9dc7-7b503534d139.gif)

Khipu 3.0
Woocomerce 4.4.1
Wordpress 5.5

**Comment by Richardmaximun** [comment]
> Al hacer click en cualquier button-toggle para activar el servicio de khipu, no hace ninguna acción. hay que hacer un segundo click para que cambie de estado admin-ajax.php responde con {"success":true,"data":false}, para el primer click y con {"success":true,"data":true} para el segundo. después de apretar guardar cambios estos no se guardan. ![bug khipu-min](https://user-images.githubusercontent.com/13381072/91076980-5187b400-e60e-11ea-9dc7-7b503534d139.gif)
> 
> Khipu 3.0 Woocomerce 4.4.1 Wordpress 5.5

1 año despues ... se mantiene el mismo bug. Aun está soportado este proyecto? 

Wordpress 5.8.1
Woocommerce 5.8.0
Khipu 3.0
